"""empty message

Revision ID: 3ac53fde9092
Revises: 
Create Date: 2022-12-01 16:47:28.700869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac53fde9092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('team', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('created', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('team', 'created_date')
    # ### end Alembic commands ###
