"""empty message

Revision ID: 43a2d2553a26
Revises: 93c73edfa2d5
Create Date: 2022-11-12 17:16:49.942712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a2d2553a26'
down_revision = '93c73edfa2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_date')
    # ### end Alembic commands ###
