"""empty message

Revision ID: 5e5d56b11220
Revises: 43a2d2553a26
Create Date: 2022-11-12 22:53:31.865699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5d56b11220'
down_revision = '43a2d2553a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_public_id_key', 'user', type_='unique')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_public_id_key', 'user', ['public_id'])
    # ### end Alembic commands ###
