"""empty message

Revision ID: 7bb673f3e5a0
Revises: fa775ca5a515
Create Date: 2022-11-13 12:07:58.812163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb673f3e5a0'
down_revision = 'fa775ca5a515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('player', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    # ### end Alembic commands ###
