"""empty message

Revision ID: 880389491110
Revises: 
Create Date: 2022-12-06 15:00:15.298089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880389491110'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'team', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_column('team', 'public_id')
    # ### end Alembic commands ###
