"""empty message

Revision ID: 93c73edfa2d5
Revises: 
Create Date: 2022-11-12 11:57:34.129981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c73edfa2d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coach', sa.Column('birthdate', sa.Date(), nullable=True))
    op.drop_column('coach', 'age')
    op.add_column('player', sa.Column('birthdate', sa.Date(), nullable=True))
    op.drop_column('player', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('age', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('player', 'birthdate')
    op.add_column('coach', sa.Column('age', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('coach', 'birthdate')
    # ### end Alembic commands ###
