"""empty message

Revision ID: fa775ca5a515
Revises: a5b96a487693
Create Date: 2022-11-13 11:30:04.601731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa775ca5a515'
down_revision = 'a5b96a487693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'created',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'created',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
