summary: Open a card package, returns two players
tags:
  - Card
consumes:
  - application/json

definitions:
  Cards:
    type: object
    properties:
      cards:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: 'Neymar'
            age:
              type: integer
              example: 30
            weight:
              type: number
              format: float
              example: 75.25
            height:
              type: integer
              format: int64
              example: 180
            role:
              type: string
              example: 'Player'   
            situation:
              type: string
              enum: ['Already have!', 'New card!']
  Error:
    type: object
    properties:
      error:
        type: string
        example: 'Still have 11:45:12 hours to open a new package!'

              
responses:
  200:
    description: A list of players cards
    schema:
      $ref: '#/definitions/Cards'
  408:
    description: Too soon to open a new package
    schema:
      $ref: '#/definitions/Error'